<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sv.asm</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>SV CPU Assembler</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(nop|jmp|[svc]_[dif](8|16|32|64)_\w*)\b</string>
			<key>name</key>
			<string>support.function.sv-asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(text|sdata|vdata)\b</string>
			<key>name</key>
			<string>storage.type.sv-asm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.label.mips</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([A-Za-z0-9_]+):</string>
			<key>name</key>
			<string>meta.function.label.mips</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.sv-asm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\$%])(0|[1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[1-9][0-9][0-9]|20[0-3][0-9]|204[0-8])\b</string>
			<key>name</key>
			<string>variable.other.register.usable.by-number.sv-asm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.sv-asm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\$%])(zero|one|pc|p|t([0-9]|[1-9][0-9]))\b</string>
			<key>name</key>
			<string>variable.other.register.usable.by-name.sv-asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\.\d+\b</string>
			<key>name</key>
			<string>constant.numeric.float.mips</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+|0(x|X)[a-fA-F0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.mips</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.mips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.mips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.mips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[rnt\\"]</string>
					<key>name</key>
					<string>constant.character.escape.mips</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.mips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.mips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.mips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[rnt\\"]</string>
					<key>name</key>
					<string>constant.character.escape.mips</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>//.*$\n?</string>
					<key>name</key>
					<string>comment.line.sv-asm</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#.*$\n?</string>
					<key>name</key>
					<string>meta.preprocessor.sv-asm</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sv-asm</string>
	<key>uuid</key>
	<string>7FD88C2E-6BE3-11D9-9A40-0011242E4184</string>
</dict>
</plist>
